name: Default CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}
    - name: Install dependencies
      run: npm ci
    - name: Validate package-lock.json changes
      run: make validate-no-uncommitted-package-lock-changes
    - name: Lint
      run: npm run lint
    - name: Test
#      run: mkdir -p coverage && npm run test -- --coverage --coverageReporters json-summary | tee ./coverage/coverage.txt
      run: npm run test -- --coverage
    - name: Build
      run: npm run build
    - name: i18n_extract
      run: npm run i18n_extract
    - name: Coverage
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        title:	Coverage Report
        summary-title:	Coverage Summary
        coverage-title: Coverage by files
        coverage-path: ./coverage/coverage.txt
